package com.example.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-10-25T23:47:10.450+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://webservice.example.com/", name = "IBankAccountService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBankAccountService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://webservice.example.com/", className = "com.example.webservice.GetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://webservice.example.com/", className = "com.example.webservice.GetUserDetailsResponse")
    public com.example.webservice.UserDetails getUserDetails(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    );

    @RequestWrapper(localName = "addUserDetails", targetNamespace = "http://webservice.example.com/", className = "com.example.webservice.AddUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "addUserDetailsResponse", targetNamespace = "http://webservice.example.com/", className = "com.example.webservice.AddUserDetailsResponse")
    public void addUserDetails(
        @WebParam(name = "user", targetNamespace = "")
        com.example.webservice.UserDetails user
    );
}
